name: Build ISO
on:
  schedule:
    - cron: "00 02 * * *"
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  json_files:
    name: Generate Build Environments
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.json.outputs.files }}
    steps:
      - uses: actions/checkout@v4
      - name: Find JSON files
        id: json
        run: |
          pushd .config
          echo "files=$(ls | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
          popd
      - run: |
          echo "${{ steps.json.outputs.files }}"

  build_iso:
    name: Build ISO
    runs-on: ubuntu-latest
    if: always() && !cancelled()
    needs: [json_files]
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        image_name:
          - automatos-server
        environment: ${{ fromJSON(needs.json_files.outputs.files) }}
    steps:
      - name: Install podman
        run: sudo apt-get update -y && sudo apt-get install -y podman

      - name: Checkout Push to Registry action
        uses: actions/checkout@v4
      
      - name: Build ISO
        id: build_iso
        uses: centos-workstation/bootc-image-builder-action@main
        with:
          image: ${{ env.IMAGE_REGISTRY }}/${{ matrix.image_name }}-${{ matrix.environment }}:latest

      - name: Upload to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image_name }}-${{ matrix.environment }}.iso
          path: ${{ steps.build_iso.outputs.output-path }}